### ISSUE TITLE
Record functionality not working in napari-script-editor v0.2.9

### ISSUE THREAD

**Issue by macromeer** [haesleinhuepf/napari-script-editor#11]
I've been using napari-script-editor version 0.2.9 to record actions in my scripts, but it seems that the record functionality is not working properly as no actions are recorded in the script.

Steps to Reproduce:

- Open napari-script-editor version 0.2.9.
- Click on the record button in the toolbar.
- Perform some actions, such as opening a file, adjusting parameters in layer controls, using other plugins
- Check the script to see if the recorded actions are present.

Expected Result:

The recorded actions should be added to the script.

Actual Result:

No actions are recorded, and the script remains unchanged.

Additional Information:

I have tried installing napari-script-editor in a fresh conda environment but the issue persists. I have also checked the README and image.sc for any information on this issue, but have not found any relevant solutions.

Environment:

napari: 0.4.17
Platform: Linux-5.19.0-38-generic-x86_64-with-glibc2.35
System: Ubuntu 22.04.2 LTS
Python: 3.9.16 | packaged by conda-forge | (main, Feb 1 2023, 21:39:03) [GCC 11.3.0]
Qt: 5.15.2
PyQt5: 5.15.9
NumPy: 1.24.2
SciPy: 1.9.1
Dask: 2023.3.2
VisPy: 0.11.0
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.2
npe2: 0.6.2

OpenGL:
GL version: 4.6.0 NVIDIA 525.105.17

**Comment by haesleinhuepf** [comment]
Hi @marco-meer ,

these things are not supported, indeed. Try the script editor together with the [napari-assistant](https://github.com/haesleinhuepf/napari-assistant) to record an image processing workflow as explained in the docs: https://github.com/haesleinhuepf/napari-assistant#usage

Best,
Robert

**Comment by macromeer** [comment]
Thamks @haesleinhuepf ! that works great with napari assistant, but not with other plugins, so still a highly welcome feature!

**Comment by haesleinhuepf** [comment]
Yes @marco-meer , it's an effort that needs to be undertaken by the napari-community. I'm just maintaining some plugins and have limited influence on the others.

Thanks for the feedback though!

**Comment by macromeer** [comment]
Your efforts are deeply appreciated. Thanks!
