### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by tischi** [haesleinhuepf/napari-script-editor#3]
What about adding this in front:

`conda create --name napari-scripting`
`conda activate napari-scripting`

...in order not to mess up people's base environment?

**Comment by haesleinhuepf** [comment]
There's this hint in the instructions:

> Get a python environment, e.g. via mini-conda. If you never used python/conda environments before, please follow the instructions here first.

Don't you think that's enough?

**Comment by tischi** [comment]
Apparently not for me 😄

**Comment by haesleinhuepf** [comment]
Then you should definitely read the page that is linked in this sentence. ;-)

I will close this as I would like to keep things simple. Thanks for the feedback anyway!

**Comment by tischi** [comment]
> Then you should definitely read the page that is linked in this sentence.

Not sure what you are referring to. Isn't that what I proposed? Or was there something else that I missed?
