### ISSUE TITLE
load and save buttons regression in 0.2.6

### ISSUE THREAD

**Issue by leec13** [haesleinhuepf/napari-script-editor#6]
Dear Robert, thank you for this incredible tool, it is changing everything in how to share my work with my colleagues in the lab !
I have updated today to releas 0.2.6 and the "load" and "save" buttons are not working anymore... back to release 0.2.5 it works perfect... (I have uninstalled the release 0.2.6 with the napari tool and re install with pip "install git+git:// ... @0.2.5")
All the best and happy new year...

**Comment by haesleinhuepf** [comment]
Hi Leon @leec13 ,

thanks for reporting this issue! I also discovered that with @jo-mueller just today. I just uploaded version 0.2.7 where the buttons should work again. If one of you two could just try and confirm, we can close this issue here.

Thanks again!

Best,
Robert

**Comment by leec13** [comment]
Hello ! Its is working perfect in release 0.2.7
 (Mac OS 10.15.7  Napari installed in conda environment with python 3.9)
All the best !

Leon

PS. Humm, what about a "scripts" site ? Like imagej/plugins page ?




Leon Espinosa
***@***.***

Equipe IAM
Instruments et Analyses pour le Microbiologie

LCB CNRS UMR 7283
31, Chemin Joseph AIGUIER
13009 MARSEILLE
Tel : 04 91 16 45 13
Cell : 06 79 25 97 40
Tel sécr.: 04 91 16 40 77
Fax : 04 91 71 89 14

**Comment by haesleinhuepf** [comment]
Thanks for checking!

> PS. Humm, what about a "scripts" site ? Like imagej/plugins page ?

If you have a script that could be of general interest, feel free to send it as github pull-request to this repository/folder:
https://github.com/haesleinhuepf/napari-script-editor/tree/main/example_scripts

If it's a more complex thing, I would recommend turning it into a proper napari-plugin, e.g. using the cookie cutter:
https://github.com/napari/cookiecutter-napari-plugin

You can then publish the plugin on the napari hub: https://napari-hub.org
Let me know if you need assistance with cookie cutting ;-)

**Comment by leec13** [comment]
Thanks !
> If you have a script that could be of general interest,

I have started to code some simple commands like "image_invert", "intensity under shapes", "crop under shape", that I need when I forgot to prepare/pre-process my image  for a specific plugin. I will see if they are stable enough to share with the community.

**Comment by haesleinhuepf** [comment]
Cool to hear @leec13 !

> I have started to code some simple commands like "image_invert"

You may have seen that already, "invert image" is a command also contained in [napari-segment-blobs-and-things-with-membranes](https://github.com/haesleinhuepf/napari-segment-blobs-and-things-with-membranes) (nsbatwm), [napari-simpleitk-image-processing](https://github.com/haesleinhuepf/napari-simpleitk-image-processing) and [napari-pyclesperanto-assistant](https://github.com/clEsperanto/napari_pyclesperanto_assistant): 

![image](https://user-images.githubusercontent.com/12660498/147970119-d00ec338-f3ad-4352-85f5-13d3166c5c40.png)

In the assistant, it has a different name, its "subtract image from scalar":

![image](https://user-images.githubusercontent.com/12660498/147969836-98f7f813-ba7a-4306-a642-523a9dbbc2cc.png)

> "crop under shape"

Some collaborators are working on this in [napari-crop](https://github.com/haesleinhuepf/napari-crop). I bet they would be happy about feedback if this works or doesn't work for your usecase!

> "intensity under shapes"

I'm not sure what this does, so again, feel free to send a PR or turn it into a plugin. The more useful examples, the better. And: nobody else has to program it if you publish it open source :-)

**Comment by leec13** [comment]
👍 !
